{% set name = "osdf-client" %}
{% set version = "6.12.1" %}
{% set date = datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/htcondor/osdf-client/archive/v{{ version }}.tar.gz
  sha256: 00d2a4d2e1ac6fdf2723ef4c9b290431b7ba0cac55ce84e89f0e736ee56b84b4

build:
  number: 0
  script:
    # when cross-compiling use 'go build -o ${PREFIX}/bin',
    # which is equivalent to 'go install'
    - go
        {% if build_platform != target_platform -%}
        build -o "${PREFIX}/bin"
        {%- else -%}
        install
        {%- endif %}
        -a
        -ldflags "-w -s -X main.version={{ version }} -X main.commit=v{{ version }} -X main.date={{ date }} -X main.builtBy=conda-forge"
        -tags forceposix
        -v
        ./cmd/stashcp
    - go-licenses save . --save_path=license-files

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

outputs:
  - name: stashcp
    files:
      - bin/stashcp*
    test:
      commands:
        - stashcp --help
        - stashcp --version
        - stashcp --list-names
    about:
      home: https://github.com/htcondor/osdf-client
      dev_url: https://github.com/htcondor/osdf-client
      summary: Command-line copy tool for the Open Science Data Federation
      license: Apache-2.0
      license_family: APACHE
      license_file:
        - LICENSE.txt
        - license-files/
      description: |
        StashCP downloads files from the
        [Open Science Data Federation](https://osdf.osg-htc.org/) through a
        series of caches. StashCP is used by multiple organizations to
        effeciently transfer input and output data.

about:
  home: https://github.com/htcondor/osdf-client
  dev_url: https://github.com/htcondor/osdf-client
  summary: StashCache/OSDF client
  license: Apache-2.0
  license_family: APACHE
  license_file:
    - LICENSE.txt
    - license-files/
  description: |
    StashCP downloads files from the
    [Open Science Data Federation](https://osdf.osg-htc.org/) through a
    series of caches. StashCP is used by multiple organizations to
    effeciently transfer input and output data.

extra:
  recipe-maintainers:
    - duncanmmacleod
